### ISSUE TITLE
the function drugPerturbationSig

### ISSUE THREAD

**Issue by wxmarch** [bhklab/PharmacoGx#101] opened 2021-12-01 14:35 UTC
Hi Christopher, 
Looking through the documentation, the function drugPerturbationSig can recreate drug signatures for each drug and preform statistical modelling of the transcriptomic response to the application of each drug.  But I didn't find the method and I am a little confused about how to recreate the drug signatures and preform statistical modelling. 

Thanks,
wxmarch

**Comment by ChristopherEeles** [comment] 2021-12-01 16:09
Hi @wxmarch,

Did you have a chance to read through the function documentation? You can do so with `?drugPerturbationSig` in your R console. The description for the function discusses modelling:

> Given a Pharmacoset of the perturbation experiment type, and a
     list of drugs, the function will compute a signature for the
     effect of drug concentration on the molecular profile of a cell.
     The algorithm uses a regression model which corrects for
     experimental batch effects, cell specific differences, and
     duration of experiment to isolate the effect of the concentration
     of the drug applied. The function returns the estimated
     coefficient for concentration, the t-stat, the p-value and the
     false discovery rate associated with that coefficient, in a 3
     dimensional array, with genes in the first direction, drugs in the
     second, and the selected return values in the third.

So the function fits a regression model to the control and the treatment of a given drug where response is the molecular metric (e.g., expression), then does ANOVA between the output of the two models.

The model formula is available in the code comment on line `92` of [drugPerturbationSig.R](https://github.com/bhklab/PharmacoGx/blob/development/R/drugPerturbationSig.R):
> using a linear model (x ~ concentration + cell + batch + duration)

Where `x` is the molecular metric for each feature. In the case of RNA it would be a metric of expression like transcripts per million (TPM).

The actual modelling with `lm` and `anova` occurs in [geneDrugPerturbation.R](https://github.com/bhklab/PharmacoGx/blob/master/R/geneDrugPerturbation.R) on lines `56` through `60`.

Let me know if you have any further questions.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by wxmarch** [comment] 2021-12-05 13:37
Hi Christopher,
Thank you for your reply. I have two more questions: Is the cMap data obtained through the function downloadPertSig('CMAP_2016') processed by the function drugPerturbationSig?  Whether the estimate in cMap data represents the drug perturbational gene-expression signatures (case vs control)?

Thanks,
wxmarch

**Comment by wxmarch** [comment] 2021-12-05 16:06
Hi Christopher,
Thank you for your reply. I have two more questions: Is the cMap data obtained through the function downloadPertSig('CMAP_2016') processed by the function drugPerturbationSig?  Whether the estimate in cMap data represents the drug perturbational gene-expression signatures (case vs control)?

Thanks,
wxmarch

**Comment by p-smirnov** [comment] 2021-12-23 18:57
@wxmarch Yes, that is the case. Its an average effect per gene between cases and controls controlling for a linear cell line factor.

**Comment by ChristopherEeles** [comment] 2022-02-14 18:34
Hi @wxmarch,

I am closing this issue, since I believe we answered your question. If that is not the case feel free to re-open it.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Closed by ChristopherEeles** 2022-02-14 18:34 UTC
Labels: question
