### ISSUE TITLE
Issue with availablePSets(): 'Error in open.connection(con, "rb") : HTTP error 500'

### ISSUE THREAD

**Issue by Pedramto89** [bhklab/PharmacoGx#94] opened 2021-06-14 19:18 UTC
I wanted to load the objects of PharmacoGx (availablePSets()) and faced with this error:

Even I attempted to use several PCs, but did not work either. 
The error is this:

Error in open.connection(con, "rb") : HTTP error 500
If anyone would help, I appreciate it.

![1](https://user-images.githubusercontent.com/85902042/121947088-e29d5800-cd12-11eb-9631-4ed1f8b59573.jpg)

**Comment by ChristopherEeles** [comment] 2021-06-14 19:39
Hi @Pedramto89,

The `availablePsets()` function accesses a web API to get the most up to date data. As a result, if the URL becomes unavailable that function can fail.

This usually only occurs transiently. I recommend waiting 10-15 minutes and trying again.

I just tested the function myself and it is working correctly. If your issue persists, please feel free to open another issue.

Best,
Chris

**Comment by Pedramto89** [comment] 2021-06-14 19:54
Thank you, Christopher. I tried many times and even after a couple of minutes, I got the error. Even, I attempted on several PCs and got the error again.
It's really amazing that you don't get the error.

**Comment by p-smirnov** [comment] 2021-06-14 20:00
@Pedramto89 A couple more things that can help: make sure your version PharmacoGx is up to date. 

I am not sure if you are accessing the internet through a VPN or hospital network, but there can be something blocking your connection. Try accessing this URL directly: http://www.orcestra.ca/api/psets/canonical 
Do you get a reply?

**Comment by ChristopherEeles** [comment] 2021-06-14 20:01
Is it possible you are having issues with your local internet connection?

Can you try to access these URLs:
http://www.orcestra.ca/api/psets/canonical
http://www.orcestra.ca/api/psets/available

If you can access those URLs, but `availablePSets` still doesn't work, please share your `sessionInfo()` so I can help futher.

Best,
Crhis

**Comment by Pedramto89** [comment] 2021-06-14 20:06
> @Pedramto89 A couple more things that can help: make sure your version PharmacoGx is up to date.
> 
> I am not sure if you are accessing the internet through a VPN or hospital network, but there can be something blocking your connection. Try accessing this URL directly: http://www.orcestra.ca/api/psets/canonical
> Do you get a reply?

Thank you. I am at the Hospital network but even, when I was using the package at home, I got the same error. 
Now, I cannot access the URL you provided. I don't know why. Now, I am at the hospital and use their connection.

**Comment by Pedramto89** [comment] 2021-06-14 20:07
> Is it possible you are having issues with your local internet connection?
> 
> Can you try to access these URLs:
> http://www.orcestra.ca/api/psets/canonical
> http://www.orcestra.ca/api/psets/available
> 
> If you can access those URLs, but `availablePSets` still doesn't work, please share your `sessionInfo()` so I can help futher.
> 
> Best,
> Chris

Thank you Christopher. I cannot access those URLs too. How can I share the info? here?

**Comment by ChristopherEeles** [comment] 2021-06-14 20:21
Hi @Pedramto89,

If you are unable to open those URLs in your browser it is likely an issue with the Hospital network.

Can you try this one:
https://www.orcestra.ca/api/psets/available

Maybe they are blocking non-HTTPS sites.

Best,
Chris

**Comment by ChristopherEeles** [comment] 2021-06-14 20:51
Hi @Pedramto89,

I was able to replicate your issue, it seems like the non-canonical PSet API is broken.

Reprex:
```r
availPSets <- availablePSets(canonical=FALSE)
```

Please update your `PharmacoGx` version using `BiocManager::install('PharmacoGx')`. You should then be able to use `availablePSets(canonical=TRUE)` to access the available PharmacoSets.

There is a problem with the API when `canonical=FALSE`, I have already opened an issue here: https://github.com/bhklab/ORCESTRA/issues/23

I will let you know here when we have resolved the problem.

Best,
Chris

**Comment by ChristopherEeles** [comment] 2021-06-14 21:14
Hi @Pedramto89,

The API has been fixed. Please retry `availablePSets()` and report if your issue is resolved?

Best,
Chris

**Comment by Pedramto89** [comment] 2021-06-14 21:22
Thank you both. Now, I can get the sets. So, I have two sets of CCLE and want to gene expression values for two different cell lines I have for drug sensitivity, looking for which ones are lethal to two groups of cell lines. How can I get this? I went over the tutorial but could not get it.

**Comment by Pedramto89** [comment] 2021-06-23 16:53
Sorry for the delayed response. I still get the same error when I try availablePSets(). Furthermore, I went to the Github repository of the package and copy and paste the last edition of the downloadPSests() R code and change the canonical to TRUE but could not download the PSet again

**Comment by ChristopherEeles** [comment] 2021-06-23 21:59
Hi @Pedramto89,

I have confirmed that the function doesn't work when `canonical=FALSE`. It looks like the API end-point is broken again. However, the default (`canonical=TRUE`) worked just fine for me. I tested it in R 4.0.5 with a fresh install of PharmacoGx from Bioconductor 3.13.

Can you post your `sessionInfo()` so I can check your R and PharmacoGx versions?

Best,
Chris

**Comment by Pedramto89** [comment] 2021-06-24 00:04
Thank you Christopher. After I updated my RGui version, in the R Studio, it worked finally

**Comment by Pedramto89** [comment] 2021-06-24 15:50
The error for downloading the PSet of CCLE_2015 solved and I got huge data of it. But, when I wanted to get the GDSC file (GDSC_2020(v2-8.2)), I faced with the same error.

The command I run : GDSCdata <- downloadPSet("GDSC_2020(v2-8.2)")
The error: Error in open.connection(con, "rb") : HTTP error 500.

**Comment by ChristopherEeles** [comment] 2021-06-24 17:11
Hi @Pedramto89,

I have requests the API be fixed again: https://github.com/bhklab/ORCESTRA/issues/23.

To get the data you want while we fix the issue, you have a few options:
(1) Click the link in the `data.frame` returned by `availablePSets`.
(2) Use the link to download the file yourself:
```
pSetDF <- availablePSets()
GDSC <- download.file(pSetDF[pSetDF$`PSet Name` == ' GDSC_2020(v2-8.2)', ]$Download)
```
See `?download.file` for more information on using this function.
(3) Download the dataset directly from ORCESTRA at https://orcestra.ca/pset/canonical

Sorry for any inconvenience.

Best,
Chris

**Comment by ChristopherEeles** [comment] 2021-06-24 17:13
Hi @Pedramto89,

The API has been fixed now and the function should work normally.

Best,
Chris

**Closed by ChristopherEeles** 2021-06-24 17:13 UTC
