### ISSUE TITLE
Expression data in CTRPv2 PSet

### ISSUE THREAD

**Issue by MomenehForoutan** [bhklab/PharmacoGx#43] opened 2017-11-29 01:18 UTC
Hi all,
It seems that the CTRPv2 PSet does not include the expression data at this stage, I was wondering if you have a version of that which includes the "rna" slot too, and if so whether you are happy to share that?

> Name:
>   CTRPv2 
> Date Created:  Wed May 11 10:20:02 2016 
> Number of cell lines:  887 
> Number of drug compounds:  545 
> **RNA:** 
> 	**Dim:  0 0** 
> Drug pertubation: 
> 	Please look at pertNumber(pSet) to determine number of experiments for each drug-cell combination.
> Drug sensitivity: 
> 	Number of Experiments:  395263 
> 	Please look at sensNumber(pSet) to determine number of experiments for each drug-cell combination.

Many thanks!
Sepideh

**Comment by bhaibeka** [comment] 2017-11-29 01:25
@p-smirnov Can you share the function to create the CCLE-CTRPv2 hybrid? It should be part of the package

**Comment by MomenehForoutan** [comment] 2017-11-29 01:27
Thanks @bhaibeka I think this is the same expression data as in the CCLE data? So all good! "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4718762/"
Thanks!
Sepideh

**Comment by bhaibeka** [comment] 2017-11-29 01:31
CReating a hybrid PSet is not that trivial (but not complicated neither), as the object must be consistent. We will send you the object we have created and the code we used.

**Comment by MomenehForoutan** [comment] 2017-11-29 02:16
Thank you so much @bhaibeka I really appreciate it!
Cheers,
Sepideh

**Comment by p-smirnov** [comment] 2017-12-12 15:37
Hi Sepideh,

Sorry for the slight delay. We have a couple of versions of the CCLE rnaseq data we are testing right now, I wanted to ask which one you think is more useful for your purposes.

Currently we have a version quantified using a HS/Stringtie pipeline and normalized as FPKM, as well as a Kallisto pipeline normalized using TPM. 

Best,
Petr

**Comment by MomenehForoutan** [comment] 2017-12-14 23:59
Hi Petr @p-smirnov,
Thanks for your reply.
Is the TPM version that you are talking about the same as the one here "https://www.synapse.org/#!Synapse:syn5612998" or you have re-analysed the raw data? I guess this is the HS/Stringtie format that you provide with the CCLE Pset as it seems to be different from the TPM version? As I have been using the RNASeq data provided through the CCLE PSet, I think it is better for me to go with the format which is available through the CCLE Pset.
Many thanks!
Sepideh

**Comment by p-smirnov** [comment] 2017-12-15 17:09
Hi Sepideh, @MomenehForoutan ,

I am actually not sure pipeline was used to create the TPM values in that synapse link. We re-quantified the data using Kallisto ourselves, @zhaleh-safikhani can you confirm what data source we used?

For our CCLE PSet released right now, we have the FPKM normalized values using a tophat-cufflinks pipeline, but we have also reanalyzed the data using the hisat stringtie which we will be updating all of our PSets with in the coming weeks. We are just working on a better method to version the objects and keep track of the pipelines used to generate them transparently to the end users right now. 

I will send a link to download the merged CCLE/CTRPv2 PSet with the exact same tophat-cufflinks RNAseq quantified data that you have been using by email, but let me know if you prefer any of the other two versions. 

Best,
Petr

**Comment by zhaleh-safikhani** [comment] 2017-12-19 19:55
Hi @MomenehForoutan,

We have the FPKM normalized quantifications using Tophat2/Cufflinks which is the version you are using now. We also have quantified FPKM values using Hisat2/StringTie pipeline and we also have TPM and estimated counts using Kallisto. All these quantifications have been estimated by running the tools on raw data(fatstq files extracted from available bam files by picard). We have all the information regarding the annotation and tools versions available if you need. 

Best,
Zhaleh

**Comment by MomenehForoutan** [comment] 2017-12-27 13:14
Thank you so much @p-smirnov and @zhaleh-safikhani!
It would be great to access the merged PSet with FPKM normalised value as I would like to keep things consistent with what I am currently working on. I really appreciate your help with this!
Cheers,
Sepideh

**Comment by MomenehForoutan** [comment] 2018-02-05 00:42
Hi @p-smirnov and @zhaleh-safikhani 
I was wondering if you could share the hybrid PSet with me? 
Many thanks!
Sepideh

**Comment by khughitt** [comment] 2019-11-12 02:11
Greetings! Any progress on this? Calling `mDataNames()` on a CTRPv2 PharmacoSet returns "rna", but indeed, attempting to retrieve that data fails:

```r
> rna_eset <- summarizeMolecularProfiles(pset, mDataType = 'rna',                                        
 cell.lines = PharmacoGx::cellNames(pset))                                                                                                           
Error in `[.data.frame`(pp, , "cellid") : undefined columns selected                                                                                                                           
Calls: summarizeMolecularProfiles -> unique -> [ -> [.data.frame -> [ -> [.data.frame  
```

**Comment by mjrmason** [comment] 2020-04-02 22:31
I, too, would like to inquire about CTRPv2's RNA. This package is amazing btw.

**Comment by mjrmason** [comment] 2020-04-20 16:38
@MomenehForoutan @bhaibeka  and @p-smirnov , I am checking with the individual who uploaded the Synapse TPM data to get any details regarding how it was processed. I'll provide them here and will ensure that he Synapse site has the details there.

**Comment by mjrmason** [comment] 2020-04-21 20:39
@MomenehForoutan  @bhaibeka and @p-smirnov I can confirm that the data was processed with Salmon 0.4.2. with the genemap flag using  ensembl v74.

**Comment by KatynaSada** [comment] 2021-11-10 11:26
@p-smirnov Can I also get the link to download the merged CCLE/CTRPv2 PSet?

**Comment by MomenehForoutan** [comment] 2022-01-06 04:26
@p-smirnov @bhaibeka  @KatynaSada 
I have got back to this awesome package again after a few years, and indeed I never received a link to download the hybrid PSet... It would be great if we could download the hybrid PSet using downloadPSet() function in the package, specifically because you are proposing to use CTRPv2 as the training data in your recent review paper (Sharifi-Noghabi et al 2021). Most of the functions in your package use a PSet object so people may not be able to easily use your functions and follow your pipeline if they do not have the hybrid PSet or if they have to go through the effort to make one themselves... I am happy to write up my own codes but rather to not reinvent the wheel and save time if it has been already done by your team. Please let me know if you won't be able to share the data, so I will write my own code/functions to do so.
Many thanks! Sepideh

**Comment by MomenehForoutan** [comment] 2022-01-06 06:41
Actually, I have just attempted to make a hybrid PSet through the below code; please let me know if that does not sound right to you or if I am missing anything here. Thanks!
Sepideh 

`
ccle <- readRDS(paste0(psetPath, "CCLE.rds"))
ctrp <- readRDS(paste0(psetPath, "CTRPv2.rds"))

## subset PSets to 
common <- intersectPSet(pSets=list(ccle, ctrp), intersectOn="cell.lines")

## Use the CTRPv2 with common cell lines, and add the RNA-seq data from CCLE
hyb <- common$CTRPv2

## add RNA data to this (*although not sure how Kallisto_0.46.1.rnaseq is different from Kallisto_0.46.1.rnaseq.count as these both seem to be log transformed; any comments on these would be appreciated*):
hyb@molecularProfiles$Kallisto_0.46.1.rnaseq <-  common$CCLE@molecularProfiles$Kallisto_0.46.1.rnaseq
`

**Comment by ChristopherEeles** [comment] 2022-01-07 22:38
Hi @MomenehForoutan,

Your code looks like it should work, however it is not recommended to access S4 object slots with the `@` operator since the object structure could change in the future. Instead you should use the included accessor method `molecularProfiles`.

So the idiomatic solution would be:
```r
molecularProfiles(hyb, "rna") <- molecularProfiles(common$CCLE, "Kallisto_0.46.1.rnaseq")
```

The structure of an S4 class is not guaranteed to be stable (for example, we may add or remove slots in the future, or rename them; indeed this is currently planned for the next Bioconductor release).  Even if this happens though, we will honour the contract of the accessor methods. 

Thus the idiomatic version is guaranteed to always work as you expect, but use of `@` may break with future updates to the package. Using accessors minimizes the chance your scripts will break in the future. This is true not just for PharmacoGx, but for all Bioconductor packages and S4 classes in general.

Regarding the difference between 'rnaseq' and 'rnaseq.counts', this is documented in the [ORCESTRA](https://orcestra.ca/) web application, which we use to version all of our data releases. You can view the description [here](https://orcestra.ca/pset/10.5281/zenodo.4721823) if you want, but the difference is that rnaseq is log2 TPM values while rnaseq.counts is log2 of the transcript counts. 

In general, TPM values should be preferred since they are normalized to RNA abundance, while counts are proportional to the quantity of RNA present in the assay.

Let me know if this solves your problem so I can close this issue.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by MomenehForoutan** [comment] 2022-01-09 21:56
Thanks @ChristopherEeles for the quick reply, and for the explanations and the links! Yes, these all solved the issue. 
Best wishes,
Sepideh

**Comment by ChristopherEeles** [comment] 2022-01-10 18:33
Awesome, feel free to open a new issue if you have further questions!

Best,
Christopher Eeles

**Closed by ChristopherEeles** 2022-01-10 18:33 UTC
