### ISSUE TITLE
Problem with downloading GDSC_2019(v2-8.0) on Windows only. 

### ISSUE THREAD

**Issue by p-smirnov** [bhklab/PharmacoGx#69] opened 2020-07-03 15:04 UTC
`downloadPSet` throws this error when downloading the file, but only on windows:
```
Error in readRDS(file.path(saveDir, pSetFileName)) : 
 ReadItem: unknown type 33, perhaps written by later version of R
```

No clue what's going on.

**Comment by ChristopherEeles** [comment] 2020-07-03 15:09
I will try to replicate it. From the error, it seems like it may be a serialization issue? Are you using R 4.0?

**Comment by p-smirnov** [comment] 2020-07-03 15:35
Yes, on both Mac and Windows. Specifically R 4.0.0 on Mac, R 4.0.2 on Windows

**Comment by p-smirnov** [comment] 2020-07-03 15:35
This was found by Hossein, I replicated.

**Comment by lykosherdshep** [comment] 2020-09-01 12:07
I met the same problem in windows R version 4.0.2 (2020-06-22)

**Comment by ChristopherEeles** [comment] 2020-09-01 13:34
I will look into this later today. Can I ask what version of PharmacoGx you are using?

**Comment by Yunuuuu** [comment] 2020-09-01 14:41
This is my sessioninfo
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] forcats_0.5.0    stringr_1.4.0    dplyr_1.0.2     
 [4] purrr_0.3.4      readr_1.3.1      tidyr_1.1.2     
 [7] tibble_3.0.3     ggplot2_3.3.2    tidyverse_1.3.0 
[10] here_0.1         PharmacoGx_2.0.5 CoreGx_1.0.2    

loaded via a namespace (and not attached):
  [1] fgsea_1.14.0                colorspace_1.4-1           
  [3] ellipsis_0.3.1              rprojroot_1.3-2            
  [5] lsa_0.73.2                  XVector_0.28.0             
  [7] fs_1.5.0                    GenomicRanges_1.40.0       
  [9] rstudioapi_0.11             SnowballC_0.7.0            
 [11] DT_0.15                     fansi_0.4.1                
 [13] lubridate_1.7.9             xml2_1.3.2                 
 [15] jsonlite_1.7.0              magicaxis_2.0.10           
 [17] broom_0.7.0                 cluster_2.1.0              
 [19] dbplyr_1.4.4                shinydashboard_0.7.1       
 [21] shiny_1.5.0                 mapproj_1.2.7              
 [23] compiler_4.0.2              httr_1.4.2                 
 [25] backports_1.1.9             assertthat_0.2.1           
 [27] Matrix_1.2-18               fastmap_1.0.1              
 [29] cli_2.0.2                   limma_3.44.3               
 [31] later_1.1.0.1               visNetwork_2.0.9           
 [33] htmltools_0.5.0             tools_4.0.2                
 [35] igraph_1.2.5                gtable_0.3.0               
 [37] glue_1.4.2                  GenomeInfoDbData_1.2.3     
 [39] RANN_2.6.1                  reshape2_1.4.4             
 [41] maps_3.3.0                  fastmatch_1.1-0            
 [43] Rcpp_1.0.5                  slam_0.1-47                
 [45] Biobase_2.48.0              cellranger_1.1.0           
 [47] vctrs_0.3.4                 gdata_2.18.0               
 [49] rvest_0.3.6                 testthat_2.3.2             
 [51] mime_0.9                    lifecycle_0.2.0            
 [53] gtools_3.8.2                zlibbioc_1.34.0            
 [55] MASS_7.3-52                 scales_1.1.1               
 [57] hms_0.5.3                   promises_1.1.1             
 [59] relations_0.6-9             parallel_4.0.2             
 [61] SummarizedExperiment_1.18.2 RColorBrewer_1.1-2         
 [63] sets_1.0-18                 curl_4.3                   
 [65] gridExtra_2.3               downloader_0.4             
 [67] stringi_1.4.6               NISTunits_1.0.1            
 [69] S4Vectors_0.26.1            plotrix_3.7-8              
 [71] caTools_1.18.0              BiocGenerics_0.34.0        
 [73] BiocParallel_1.22.0         GenomeInfoDb_1.24.2        
 [75] rlang_0.4.7                 pkgconfig_2.0.3            
 [77] matrixStats_0.56.0          bitops_1.0-6               
 [79] pracma_2.2.9                lattice_0.20-41            
 [81] htmlwidgets_1.5.1           tidyselect_1.1.0           
 [83] plyr_1.8.6                  magrittr_1.5               
 [85] R6_2.4.1                    IRanges_2.22.2             
 [87] gplots_3.0.4                generics_0.0.2             
 [89] DelayedArray_0.14.1         DBI_1.1.0                  
 [91] sm_2.2-5.6                  withr_2.2.0                
 [93] pillar_1.4.6                haven_2.3.1                
 [95] RCurl_1.98-1.2              modelr_0.1.8               
 [97] crayon_1.3.4                KernSmooth_2.23-17         
 [99] readxl_1.3.1                grid_4.0.2                 
[101] data.table_1.13.0           marray_1.66.0              
[103] blob_1.2.1                  piano_2.4.0                
[105] reprex_0.3.0                digest_0.6.25              
[107] xtable_1.8-4                httpuv_1.5.4               
[109] stats4_4.0.2                munsell_0.5.0              
[111] celestial_1.4.6             tcltk_4.0.2                
[113] shinyjs_1.1

**Comment by ChristopherEeles** [comment] 2020-09-01 17:03
Hi @Yunuuuu,

I have replicated your issue with both the release and development version of PharmacoGx. The problem is due to an incorrect URL in the availablePSets() function for GDSC_2019(2-8.0). I have contacted my colleagues to correct the URL - we fetch it from an API for the Orcestra web application (https://orcestra.ca) - but it may take a day or two until it is fixed.

In the mean time you can download the correct version from this URL:
https://orcestra.ca/10.5281/zenodo.3905496

I tested it and the file loads fine using readRDS on Windows 10.

I will reply to this thread once we get the new URL setup so we can close the issue.

Best,
Christopher Eeles
Software Developer
BHK Laboratory

**Comment by Yunuuuu** [comment] 2020-09-02 15:56
Dear developer, Thanks for your help, it seems the dataset GDSC_2020(v2-8.2) isn't the only dataset with a error in downloading,  the CCLE_2015 dataset exists the same problem when downloaded, I havn't tried other datasets because of my slow network,

**Comment by ChristopherEeles** [comment] 2020-09-02 16:01
Hi @Yunuuuu,

Thanks for the heads up. I will run some more systematic tests today and work on correcting the issue ASAP.

In the meantime, all PSets can be downloaded from https://orcestra.ca.

Best,
Christopher Eeles
Software Developer
BHK Laboratory

**Comment by ChristopherEeles** [comment] 2020-09-03 21:36
Hi @Yunuuu,

The issue was caused by failure to tell the download function that the file was binary. Apparently on Windows this writes additional meta data to the file when it is downloaded, which makes it unreadable in R.

I have correct the issue in both the development and release branches on Bioconductor, which should be available after the next build tomorrow.

In the interim, you could download and install the release version with the updated code from our GitHub with the following code:

`devtools::install_github('bhklab/PharmacoGx', ref='RELEASE_3_11')`

If you have further difficulties please don't hestitate to open another issue.

Best,
Christopher Eeles
Software Developer
BHK Laboratory
Christopher Eeles
Software

**Closed by ChristopherEeles** 2020-09-03 21:36 UTC

**Comment by Yunuuuu** [comment] 2020-09-23 14:59
Thanks for ur help!!  I'll test it
