### ISSUE TITLE
PharmacoGx and ggplot2 function conflict? 

### ISSUE THREAD

**Issue by DGendoo** [bhklab/PharmacoGx#90] opened 2021-05-01 15:32 UTC
Hello team, 
I've downloaded the latest R version (4.0.5) and updated to the latest Bioconductor version (3.12).
I then attempted to installed the latest PharmacoGx (2.2.4) to update from the last version I was using. 
However now the issue is that when loading the library, it 'hangs' and doesn't go further beyond mentioning a conflict with a ggplot2 function (see image). 
So now if I attempt to load RData  objects containing my drug perturbation signatures or PharmacoSets, I'm not able to load them. 

I've tried updating ggplot2 and then updating the PharmacoGx installation with dependencies, but I can't seem to shake the error. 
Any tips on how to get around this? 

PS - I've attempted to empty my workspace/sessions to make sure that I have clean sessions, and also I've run on RStudio and R seperately, I still get the same error. 

Thanks!

<img width="649" alt="Screenshot 2021-05-01 at 15 18 03" src="https://user-images.githubusercontent.com/10535081/116787097-193c4d80-aa9a-11eb-9ec2-ad60d5da3f93.png">

**Comment by p-smirnov** [comment] 2021-05-01 16:03
Is this under Linux, Mac or Windows? 

Usually the ggplot warning is unrelated to this issue, and it’s caused by a different dependency. Can you try loading the `magicaxis` package on its own (that’s a common culprit)?

**Comment by p-smirnov** [comment] 2021-05-01 16:11
If you’re on a Mac, a likely issue is a bad Xquartz install. Try reinstalling the latest version, and if that doesn’t help downgrading to 2.7.11

**Comment by DGendoo** [comment] 2021-05-01 16:50
Thanks Petr. 
Yes this is on a Mac (forgot to mention that sorry). I did try to install this on a Windows and that has worked, so its definitely an issue with my mac. 
The magicaxis package was also hanging. I've tried the latest Xquartz but that hasn't solved the issue, tried downgrading to 2.7.11 but that hasn't solved it either. Any idea?  🤔

**Comment by p-smirnov** [comment] 2021-05-01 16:56
I’ll ask Ian to take a look, he was able to solve it recently.

**Comment by DGendoo** [comment] 2021-05-01 16:56
I should mention that Xquartz is working. The quartz() function does run within R.

**Comment by iamsinht** [comment] 2021-05-01 18:35
Deena, can you try to load with verbose?

library(PharmacoGx, verbose=TRUE)

**Comment by DGendoo** [comment] 2021-05-01 21:16
Hi Ian. 
<img width="455" alt="Screenshot 2021-05-01 at 22 13 07" src="https://user-images.githubusercontent.com/10535081/116795166-d9da2500-aaca-11eb-9937-c928c92de58c.png">

Same as before (see image):

**Comment by DGendoo** [comment] 2021-05-01 22:27
I finally fixed it! Seems it was indeed a problem with XQuartz - I have MacOS Mojave and Xquartz reopens everytime I force quit it (it's on a loop). Took a number of uninstalls/reinstalls and cleaning x11 files to resolve the issue, and then reinstalling PharmacoGx. Hopefully this holds! 
Thanks @p-smirnov @iamsinht

**Comment by ChristopherEeles** [comment] 2021-05-04 16:28
Hi @DGendoo,

It seems like this issue has been resolved. As such I am closing it, please do not hesitate to open another if you still have trouble with PharmacGx.

Best,
Chris

**Closed by ChristopherEeles** 2021-05-04 16:28 UTC
