### ISSUE TITLE
Beat AML and Smiles missing 

### ISSUE THREAD

**Issue by SafiaSafa** [bhklab/PharmacoGx#95] opened 2021-07-22 18:54 UTC
Hello ,
I had to reinstall my Rstudio and I also reinstall to PharmacoGx package .  
```
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c('PharmacoGx',"org.Hs.eg.db","AnnotationDbi"))
```

In the previous version there was data for BeatAML ( https://doi.org/10.1038/s41586-018-0623-z.) and aslo the SMILES  associated to compound (for the GDSC dataset at least). When I re-install the package those information were not  available anymore.

I wanted to know if there is a way to have acces to those data?

This is my session info : 
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8    LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scales_1.1.1                reshape2_1.4.4              drc_3.0-1                   MASS_7.3-54                
 [5] cowplot_1.1.1               plotly_4.9.4.1              dplyr_1.0.7                 tidyr_1.1.3                
 [9] synergyfinder_2.0.12        DT_0.18                     shinyjs_2.0.0               shinydashboard_0.7.1       
[13] shiny_1.6.0                 readxl_1.3.1                forcats_0.5.1               ggplot2_3.3.5              
[17] org.Hs.eg.db_3.10.0         AnnotationDbi_1.48.0        PharmacoGx_1.17.1           stringr_1.4.0              
[21] gep2pep_1.6.0               signatureSearch_1.0.4       SummarizedExperiment_1.16.1 DelayedArray_0.12.3        
[25] BiocParallel_1.20.1         matrixStats_0.59.0          Biobase_2.46.0              GenomicRanges_1.38.0       
[29] GenomeInfoDb_1.22.1         IRanges_2.20.2              S4Vectors_0.24.4            BiocGenerics_0.32.0        
[33] Rcpp_1.0.7                 

loaded via a namespace (and not attached):
  [1] utf8_1.2.1                    tidyselect_1.1.1              RSQLite_2.2.7                
  [4] htmlwidgets_1.5.3             munsell_0.5.0                 codetools_0.2-18             
  [7] withr_2.4.2                   colorspace_2.0-2              GOSemSim_2.12.1              
 [10] DOSE_3.12.0                   labeling_0.4.2                repo_2.1.5                   
 [13] slam_0.1-48                   urltools_1.7.3                GenomeInfoDbData_1.2.2       
 [16] polyclip_1.10-0               bit64_4.0.5                   farver_2.1.0                 
 [19] rhdf5_2.30.1                  downloader_0.4                TH.data_1.0-10               
 [22] vctrs_0.3.8                   generics_0.1.0                BiocFileCache_1.10.2         
 [25] sets_1.0-18                   lsa_0.73.2                    R6_2.5.0                     
 [28] graphlayouts_0.7.1            celestial_1.4.6               bitops_1.0-7                 
 [31] cachem_1.0.5                  fgsea_1.12.0                  gridGraphics_0.5-1           
 [34] assertthat_0.2.1              promises_1.2.0.1              multcomp_1.4-17              
 [37] ggraph_2.0.5                  enrichplot_1.6.1              gtable_0.3.0                 
 [40] sandwich_3.0-1                tidygraph_1.2.0               rlang_0.4.11                 
 [43] splines_3.6.3                 lazyeval_0.2.2                europepmc_0.4                
 [46] abind_1.4-5                   BiocManager_1.30.16           yaml_2.2.1                   
 [49] httpuv_1.6.1                  qvalue_2.18.0                 clusterProfiler_3.14.3       
 [52] tools_3.6.3                   relations_0.6-9               tcltk_3.6.3                  
 [55] ggplotify_0.0.7               ellipsis_0.3.2                gplots_3.1.1                 
 [58] jquerylib_0.1.4               RColorBrewer_1.1-2            ggridges_0.5.3               
 [61] plyr_1.8.6                    visNetwork_2.0.9              progress_1.2.2               
 [64] zlibbioc_1.32.0               purrr_0.3.4                   RCurl_1.98-1.3               
 [67] prettyunits_1.1.1             viridis_0.6.1                 zoo_1.8-9                    
 [70] haven_2.4.1                   ggrepel_0.9.1                 cluster_2.1.2                
 [73] magrittr_2.0.1                data.table_1.14.0             openxlsx_4.2.4               
 [76] DO.db_2.9                     triebeard_0.3.0               RANN_2.6.1                   
 [79] mvtnorm_1.1-2                 SnowballC_0.7.0               hms_1.1.0                    
 [82] mime_0.11                     xtable_1.8-4                  XML_3.99-0.3                 
 [85] rio_0.5.27                    gridExtra_2.3                 compiler_3.6.3               
 [88] tibble_3.1.2                  maps_3.3.0                    KernSmooth_2.23-20           
 [91] crayon_1.4.1                  htmltools_0.5.1.1             later_1.2.0                  
 [94] DBI_1.1.1                     tweenr_1.0.2                  ExperimentHub_1.12.0         
 [97] dbplyr_2.1.1                  rappdirs_0.3.3                Matrix_1.3-4                 
[100] car_3.0-11                    readr_2.0.0                   marray_1.64.0                
[103] igraph_1.2.6                  pkgconfig_2.0.3               sm_2.2-5.6                   
[106] rvcheck_0.1.8                 foreign_0.8-75                magicaxis_2.2.1              
[109] piano_2.2.0                   xml2_1.3.2                    foreach_1.5.1                
[112] annotate_1.64.0               bslib_0.2.5.1                 XVector_0.26.0               
[115] digest_0.6.27                 pracma_2.3.3                  graph_1.64.0                 
[118] cellranger_1.1.0              fastmatch_1.1-0               GSEABase_1.48.0              
[121] curl_4.3.2                    gtools_3.9.2                  lifecycle_1.0.0              
[124] jsonlite_1.7.2                Rhdf5lib_1.8.0                carData_3.0-4                
[127] mapproj_1.2.7                 viridisLite_0.4.0             limma_3.42.2                 
[130] fansi_0.5.0                   pillar_1.6.1                  lattice_0.20-44              
[133] survival_3.2-11               fastmap_1.1.0                 httr_1.4.2                   
[136] plotrix_3.8-1                 GO.db_3.10.0                  interactiveDisplayBase_1.24.0
[139] glue_1.4.2                    zip_2.2.0                     iterators_1.0.13             
[142] BiocVersion_3.10.1            bit_4.0.4                     sass_0.4.0                   
[145] ggforce_0.3.3                 stringi_1.6.2                 HDF5Array_1.14.4             
[148] NISTunits_1.0.1               blob_1.2.1                    AnnotationHub_2.18.0         
[151] caTools_1.18.2                memoise_2.0.0                
```

**Comment by ChristopherEeles** [comment] 2021-07-22 19:02
Hi @SafiaSafa,

Is there anyway you can update your R version? You are two major release behind (3.6 -> 4.0 -> 4.1). As such, you are using a very old version of PharmacoGx. The current RELEASE is 2.4.0 on Bioconductor 3.13.

We have also introduced a new parameter for both `availablePSets` and `downloadPSet` called `canonical`. It defaults to `TRUE`, meaning it only shows the PSets which we recreated from raw data. To view other PSets, use: `availablePSets(canonical=FALSE)`.

If that does not work, all of our PSets are version controlled via the ORCESTRA web app, which you can access [here](https://orcestra.ca/pset).

Best,
Christopher Eeles
Software Developer @ BHKLab
PMCRT @ UHN

**Comment by SafiaSafa** [comment] 2021-08-12 23:10
Hi @ChristopherEeles,

Thank you, I was able to download the data from the ORCESTRA web page. But SMILES were not available for the BeatAML dataset. Is this information available in PharmacoGx and I could not find it?Or should I email the authors of the Beat AML article to get this information?

**Comment by ChristopherEeles** [comment] 2021-08-13 15:09
Hi @SafiaSafa,

I mainly develop the infrastructure and analysis tools so I am not sure I am the best person to answer your question.  I downloaded BeatAML with `downloadPSet('BeatAML_2018')` today and have confirmed there are no smiles present in the dataset.

Whether they were there in the past I am not sure. Perhaps @p-smirnov knows? If not I would recommend you move your issue to the ORCESTAR GitHub repo, since that is where PSet creation occurs. That can be done [here](https://github.com/bhklab/ORCESTRA/issues).

Best,
Chris

**Comment by SafiaSafa** [comment] 2021-08-17 17:56
Thank you @ChristopherEeles, I will put an issue to the ORCESTRA GitHub.

**Comment by ChristopherEeles** [comment] 2022-02-14 18:50
Hi @SafiaSafa,

I closed this issue in ORCESTRA. If you feel it is unresolved feel free to re-open it.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Closed by ChristopherEeles** 2022-02-14 18:50 UTC
